// The small sentences under each solution step, for parents and kids who read.
// All of them live here, keyed by name, so another language can be added as one more block.
// {a} in a sentence is filled in with that value.
import { DESERT_WORDS } from './sol-words-desert.js';
import { VOLCANO_WORDS } from './sol-words-volcano.js';
import { SPACE_WORDS } from './sol-words-space.js';

const WORDS = {
  en: {
    // adding and taking away
    'frames': 'Put the dots in ten-frames.',
    'fullFrames': 'Each full frame is 10. Then count the rest.',
    'countDots': 'Count the dots one by one.',
    'fill10': 'Fill the first frame up to 10: {a} more.',
    'ten+': '10 and {a} more make {b}.',
    'toTen': 'Add {a} first to reach {b}, a whole ten.',
    'tenMore': '{b} and {a} more make {c}.',
    'downToTen': 'Take away {a} first to get down to {b}, a whole ten.',
    'double': 'A double: the same number twice.',
    'nearDouble': '{a} + {b} is one more than the double {a} + {a}.',
    'hops': 'Start at {a} and hop {b} forward.',
    'hopsBack': 'Start at {a} and hop {b} back.',
    'split': 'Split both numbers into tens and ones.',
    'tens': 'Add the tens.',
    'ones': 'Add the ones.',
    'newTen': 'Ten ones make a new ten. {a} ones stay.',
    'together': 'Put the tens and ones together.',
    'tensJump': 'Jump by tens.',
    'crossOut': 'Take {a} away. Count what is left.',
    'backTo10': 'Take away {a} first to get down to 10.',
    'thenRest': 'Then take away the other {a}.',
    'breakTen': 'Not enough ones. Break a ten into 10 ones.',
    'subOnes': 'Take away the ones.',
    'subTens': 'Take away the tens.',
    'countUp': 'Count up from {a} to {b}.',
    'missingAdd': 'Count the empty spaces up to {a}.',
    'place': 'Each rod is 10 and each cube is 1.',
    'placeSum': '{a} tens and {b} ones.',
    // comparing
    'cmpWork': 'Work out each side first.',
    'cmpLine': 'The number further right on the line is bigger.',
    'cmpSame': 'Both are at the same place, so they are equal.',
    'cmpTens': 'Compare the tens first.',
    'cmpOnes': 'Same tens, so compare the ones.',
    // rows and patterns
    'step': 'Every jump is {a}.',
    'grow': 'Each jump is 1 bigger than the last.',
    'nextJump': 'So the next jump is {a}.',
    'repeat': 'This part repeats again and again.',
    'repeatNext': 'Keep repeating to find the next one.',
    // true or false, find all, pairs
    'workOut': 'Work it out.',
    'tfYes': 'Both sides are the same, so it is right.',
    'tfNo': 'The sides are different, so it is wrong.',
    'checkEach': 'Work out every card. Only the ones that make {a} count.',
    'pairsFind': 'Look for two cards that make {a}.',
    // times
    'rows': '{a} rows of {b}.',
    'skip': 'Count on by {a} for each row.',
    'split5': 'Cut it into 5 rows and {a} more.',
    'times10': 'Times 10 puts a 0 on the end.',
    'times9': '9 rows is 10 rows take away one row.',
    'times1': 'One row of {a} is just {a}.',
    'mulMiss': 'Jump by {a} until you reach {b}. Count the jumps.',
    // puzzles
    'trySigns': 'Try each sign and see which one works.',
    'leftToRight': 'Work from left to right.',
    'pyrRule': 'Each brick is the two bricks under it added together.',
    'pyrDown': 'Going down: the top brick take away the one you know.',
    'balLeft': 'Work out the side you know.',
    'balRight': 'The other side must be the same.',
    'sameValue': 'Work out the value. Find the card with the same value.',
    // shapes
    'corners': 'Count the corners one by one.',
    'sidesTarget': 'The top shape has {a} sides.',
    'sidesMatch': 'Count the sides of each shape. Tap the ones with {a}.',
    'mirror': 'Fold along the line. Each square lands just as far away on the other side.',
    'mirrorWrong': 'A plain copy or an upside-down picture does not fold onto it.',
    'sphere': 'Round like a ball: a sphere.',
    'cube': 'A box with square faces: a cube.',
    'cylinder': 'Round and flat on both ends, like a can: a cylinder.',
    'cone': 'Round at the bottom with a point on top: a cone.',
    'triSize': 'Triangles made of {a} small parts.',
    'triSmall': 'Count the small triangles first.',
    'triTotal': 'Add up all the sizes.',
    'sqxSmall': 'The two lines make 4 small triangles.',
    'sqxBig': 'Each half of the square is a big triangle: 4 more.',
    // measuring and money
    'ruler': 'The snake starts at {a} and ends at {b}.',
    'rulerDiff': 'Its length is the jump from {a} to {b}.',
    'clips': 'Count the paper clips along the snake.',
    'guess': 'Lay the small square along the snake again and again.',
    'coinsSort': 'Start with the biggest coins and keep a running total.',
    'payCheck': 'Add up each handful. Only one is exactly {a}.',
    'fewest': 'Take the biggest coin that fits, again and again.',
    'change': 'Count up from the price to what you paid.',
    // stories
    'storyStart': 'At the start there are {a}.',
    'storyAway': '{a} go away.',
    'storyMore': '{a} more come.',
    'storyEnd': 'Now there are {a}.',
    'storyMissing': 'Start and end are known. The difference went away.',
    // what went wrong
    'oopsNewTen': 'The new ten was left out.',
    'oopsExtraTen': 'One ten too many.',
    'oopsBorrow': 'The small ones were taken from the big ones. First break a ten.',
    'oopsTookAway': 'That is taking away. Here we add.',
    'oopsAdded': 'That is adding. Here we take away.',
    'oopsOne': 'Just one off. Count again carefully.',
    'oopsSwap': 'The tens and ones got swapped. Rods are tens, cubes are ones.',
    'oopsHave': 'That is the number you already have.',
    'oopsSym': 'The open side of the sign always faces the bigger number.',
    'oopsRow': 'One row too many or too few.',
    'oopsPlus': 'That is adding the numbers. Times means rows of the same size.',
    'oopsStep': 'Check the jump size between the numbers.',
    'oopsWhole': 'That is the whole side. The ? is only part of it.',
    'oopsRuler': 'The snake does not start at 0. Count from where it starts.',
    'oopsStory': 'Look again: did they go away, or did more come?',

    // ---------- Ocean ----------
    // comparing big numbers
    'cmpLonger': 'More digits means a bigger number.',
    'cmpPlace': 'Same number of digits. From the left, the first digit that is different decides.',
    // place value
    'placeCount': 'Count each kind: the biggest ones first.',
    'placeJoin': 'Put all the parts together.',
    'digitPlace': 'The {a} stands in the {b} column, so it is worth {c}.',
    'digitSum': 'The number is made of these parts.',
    'times10Row': 'Each step is × 10.',
    'oneMoreZero': '× 10 moves every digit one place to the left, and a 0 fills the ones.',
    'timesZeros': '× {a} puts {b} zeros on the end.',
    'divZeros': '÷ {a} takes {b} zeros off the end.',
    'timesZeros1': '× 10 puts a 0 on the end.',
    'divZeros1': '÷ 10 takes a 0 off the end.',
    'timesTens': '× {a} is × {b} and then × 10.',
    'roundBetween': 'It sits between {a} and {b}.',
    'roundNear': '{a} is nearer to {b}: only {c} away.',
    'estWork': 'Work it out first.',
    // columns
    'colLine': 'Line up the ones, the tens and the hundreds.',
    'colFirst': 'Start with the ones.',
    'colFirstCarry': 'Start with the ones. That is 10 or more: write {a} and carry 1 to the next column.',
    'colNext': 'Now the next column.',
    'colCarry': 'That is 10 or more: write {a} and carry 1 to the next column.',
    'colFirstSub': 'Start with the ones: take away.',
    'colNextSub': 'Now the next column.',
    'colBorrow': '{a} is less than {b}: take 1 from the next column, so {a} becomes {c}.',
    'undoAdd': 'The ? plus {b} makes {a}, so take {b} away from {a}.',
    'undoSub': 'Taking the ? from {a} leaves {b}, so the ? is {a} − {b}.',
    // times and sharing
    'mulSplit': 'Cut the big number into hundreds, tens and ones.',
    'mulSplit2': 'Cut the big number into tens and ones.',
    'mulSplit4': 'Cut the big number into thousands, hundreds, tens and ones.',
    'mulEach': 'Multiply every part by {a}.',
    'addParts': 'Add the parts.',
    'undoTimes': 'Undo × {a} with ÷ {a}.',
    'chunks': 'Take out a big chunk of tens first, then the rest.',
    'checkTimes': 'Check: {a} × {b} = {c}.',
    'cut4': 'Cut both numbers into tens and ones. The rectangle gets 4 parts.',
    'mulEachPart': 'Work out each part.',
    'shareRows': 'Share {a} into {b} equal rows.',
    'divCheck': 'Check with times: {a} × {b} = {c}.',
    'divWhole': '{a} groups of {b}.',
    'divGroups': 'How many groups of {a} make {b}?',
    'remFit': 'Fill {a} equal rows: {b} in each.',
    'remLeft': 'The {a} that do not fit are left over.',
    'remBack': 'Add back the {a} left over.',
    'dealFirst': 'Deal the biggest blocks first, the same to every chest.',
    'dealNext': 'Deal the next blocks.',
    'dealBreak': 'Break what is left into smaller blocks.',
    // puzzles
    'mdWhole': 'Find the whole missing number first.',
    'mdDigit': 'Now read the hidden digit.',
    'machineBack': 'Run the machine backwards.',
    'undoLast': 'Undo the last step first: {a}.',
    'undoFirst': 'Then undo {a}.',
    'sqSize': 'Squares {a} by {a}: {b}.',
    'sqTotal': 'Add up all the sizes.',
    'stairsPush': 'Push the steps out to the corner: the fence stays just as long.',
    'perimWalk': 'Walk around the edge and add up the sides.',
    'halfOf': 'Half of {a} is {b}.',
    'thenPart': 'Then cut that into {a} equal parts.',
    // fractions
    'fracName': '{a} equal pieces. {b} are coloured.',
    'fracName1': '{a} equal pieces. 1 is coloured.',
    'fracSameBottom': 'The pieces are the same size, so more pieces is more.',
    'fracSameTop': 'The same number of pieces: a smaller bottom number means bigger pieces.',
    'fracLook': 'Put the two bars one under the other.',
    'fracSameCut': 'Cut both into the same number of pieces, then compare.',
    'fracOf1': 'Cut {a} into {b} equal groups: {c} in each.',
    'fracOfN': 'Take {a} of the groups.',
    'fracSameAmount': 'The same amount of chocolate, cut into more pieces.',
    'fracTimesBoth': 'Multiply the top and the bottom by the same number.',
    // time
    'clockHour': 'The short hand points at {a}.',
    'clockPast': 'The short hand has passed {a}, but not the next number.',
    'clockMin': 'The long hand counts minutes: 5 for every number.',
    'clockStart': 'The clock shows {a}.',
    'toHour': 'First go up to the whole hour: {a} minutes. Then {b} more.',
    'addMin': 'Add {a} minutes.',
    // angles
    'angleOverlay': 'Put one angle on top of the other. The wider opening is bigger.',
    'angleSame': 'Put one angle on top of the other: they open just as wide.',
    'angleSlices': 'Count the {a}° slices.',
    'angleLess90': 'Smaller than a square corner (90°).',
    'angle90': 'A square corner is 90°.',
    'angleMore90': 'Wider than a square corner (90°), but not yet a straight line (180°).',
    'angle180': 'A straight line is 180°.',
    'straight180': 'A straight line is 180°. The two parts add up to it.',
    'rightIs': 'A right angle is a square corner: 90°.',
    'rightCheck': 'Put a square corner on each one. Only the ones that fit exactly count.',
    // area and fences
    'areaRows': '{a} rows of {b} squares.',
    'areaWhole': 'Fill in the missing corner: a whole rectangle.',
    'areaCut': 'Then take the corner away again.',
    'perimL': 'Push the sides of the missing corner out: the fence stays just as long.',
    'buildCheck': 'Work out rows × columns for each one.',
    // shapes, turns and nets
    'parSides': 'Parallel sides point the same way and never meet, like train rails.',
    'parNone': 'No two sides point the same way.',
    'oddPar': 'Three shapes have two pairs of parallel sides. The odd one does not.',
    'propRight': 'Look for a square corner.',
    'propPar': 'Look for two sides that point the same way.',
    'propEq': 'Look for shapes whose sides are all the same length.',
    'propCheck': 'Check every shape.',
    'turnAll': 'Turn the shape a quarter turn at a time. The answer is one of these.',
    'turnFlip': 'The others are flipped over. Turning never makes a flipped copy.',
    'netFaces': 'Fold it up: each of the 6 squares becomes a different face.',
    'netBad': 'In the others, two squares land on the same face (red).',
    // chances and charts
    'mostCount': 'Count each colour. The most marbles is the most likely.',
    'spinLook': 'Some colours are cut into more than one piece.',
    'spinParts': 'Count the equal pieces of each colour. The most pieces is the most likely.',
    'bagOf': '{a} of the {b} marbles have this colour.',
    'bagsPart': 'Make each bag a bar. The longer red part is more likely.',
    'chartTallest': 'The tallest bar is the most.',
    'chartRead': 'Go from the top of the bar across to the numbers.',
    'chartDiff': 'Take the smaller one away from the bigger one.',
    'dieFair': 'A fair die comes up about the same for every face. {a} came up far more.',
    // stories
    'storyPlan': 'Write the story as one line of math.',
    'firstTimes': 'Do × and ÷ first.',
    'storyFinish': 'Then finish it: {a}.',
    // what went wrong (Ocean)
    'oopsPlaces': 'The right digits, in the wrong places.',
    'oopsCountAgain': 'One kind was counted wrong. Count each kind again.',
    'oopsFace': 'That is only the digit. Its place makes it worth more.',
    'oopsPlaceOff': 'One place off. Count the columns from the right: ones, tens, hundreds …',
    'oopsZeros': 'One zero too many or too few.',
    'oopsFar': 'That end is further away.',
    'oopsCarry': 'A carried 1 was left out, or added where it does not belong.',
    'oopsColumnOff': 'One column is off. Work each column again.',
    'oopsBorrowCol': 'Check the column you took 1 from: it is 1 smaller now.',
    'oopsPartMul': 'Every part must be multiplied by {a}, the ones too.',
    'oopsFour': 'All four parts count, not only two.',
    'oopsRemBig': 'What is left must be less than {a}, or everyone could get one more.',
    'oopsDealLeft': 'The leftovers were thrown away. Break them into smaller blocks and keep dealing.',
    'oopsOrder': 'Undo the last step first, then the first one.',
    'oopsArea': 'That counts the squares inside. The fence goes around the edge.',
    'oopsFence': 'That is the fence around it. Area counts the squares inside.',
    'oopsSide': 'A side was missed or counted twice.',
    'oopsEmpty': 'Those are the empty pieces. Count the coloured ones.',
    'oopsFlip': 'Upside down: the bottom number is how many pieces in all.',
    'oopsCountPieces': 'Count all the pieces again, coloured and empty.',
    'oopsFracBottom': 'A bigger bottom number means smaller pieces.',
    'oopsOnePart': 'That is one group. Take {a} groups.',
    'oopsRest': 'That is the part that is left.',
    'oopsHourHand': 'The short hand is between two numbers: take the one it has passed.',
    'oopsHands': 'The hands got swapped: the short one shows the hour.',
    'oopsNextHour': 'Past 60 minutes the hour moves on by one.',
    'oopsArms': 'Long arms do not make an angle bigger. Look at the opening.',
    'oopsOther': 'That is the angle on the other side of the line.',
    'oops180': 'A straight line is 180°.',
    'oopsFewer': 'That colour has fewer.',
    'oopsOtherColours': 'That counts the other colours.',
    'oopsAll': 'That is all the marbles. Count only this colour.',
    'oopsMoreRed': 'More red marbles is not enough. Look at how much of the whole bag is red.',

    // ---------- Candy Factory ----------
    // factors and primes
    'boxCount': 'Count the candies in each box.',
    'pairsUp': 'Try 1 row, 2 rows, 3 rows … Each one that shares out evenly is a box. Stop when the rows pass the columns.',
    'primeOnly': 'A prime makes only one long row: 1 × itself. Any other number splits into smaller rows.',
    // divisibility
    'rule2': 'Passes ÷2 when the last digit is even: 0, 2, 4, 6 or 8.',
    'rule5': 'Passes ÷5 when the last digit is 0 or 5.',
    'rule10': 'Passes ÷10 when the last digit is 0.',
    'rule3': 'Add the digits. Passes ÷3 when the sum is in the 3 times table.',
    'rule9': 'Add the digits. Passes ÷9 when the sum is 9, 18, 27 …',
    'rule4': 'Only the last two digits matter. Passes ÷4 when they are in the 4 times table.',
    'rule6': 'Passes ÷6 when it passes ÷2 and ÷3 both.',
    'tryEach': 'Try each machine. Only one shares out with nothing left.',
    'next9': 'The digits must add up to {a}.',
    // equal fractions
    'cutMore': 'Cut every piece into {a}.',
    'timesBoth': 'The bottom is × {a}, so the top is × {a} too.',
    'joinPieces': 'Every big piece is {a} small pieces joined together.',
    'divBoth': '÷ {a} on the top and on the bottom.',
    // mixed numbers
    'wholeCakes': 'Each whole cake is {a} slices. Add the slices that are left.',
    'cakesOfSlices': 'Every {a} slices make one whole cake.',
    'mixSplit': 'Make whole cakes of {a} slices: {b} whole, {c} left over.',
    'wholeAsSlices': '{a} whole cakes are {b} slices of {c}.',
    // adding and taking slices
    'sameCuts': 'The pieces stay the same size, so the bottom stays {a}. Add the tops.',
    'robotWrong': 'The robot added the bottoms too. The pieces did not get smaller.',
    'addTops': 'Same size pieces: add the tops. The bottom stays {a}.',
    'takeTops': 'Same size pieces: take away the tops. The bottom stays {a}.',
    'commonCut': 'Cut both into the same size pieces: {a} pieces each.',
    'timesBothShort': 'Top and bottom times the same number.',
    // trays and scoops
    'trayCut': 'Cut {a} one way and {b} the other: {c} small pieces.',
    'trayBoth': 'Count the pieces in both colours: {a} × {b}.',
    'scoopCount': 'Each whole makes {a} scoops.',
    'scoopGroup': 'Put the scoops in groups of {a}.',
    'sameCutDiv': 'Cut both into the same size pieces.',
    'fitsTimes': 'How many times does {a} fit into {b}?',
    'scoopBack': 'Each whole makes {a} scoops, so {b} scoops fill {c} wholes.',
    // decimals
    'gridRows': 'Each full row is 0.1. Each small square is 0.01.',
    'lineTenths': 'From {a} to {b} is cut into 10 steps of 0.1.',
    'tenthsAre': '{a} tenths.',
    'hundredthsAre': '{a} hundredths.',
    'decSameLen': 'Give both the same number of digits after the dot.',
    'decCompare': 'Now compare them like whole numbers.',
    'lineDots': 'Line up the dots. Fill empty places with 0.',
    'likeWhole': 'Add or take away like whole numbers. The dot stays in its place.',
    'shiftLeft': 'Every digit moves 1 place to the left. The dot stays.',
    'shiftLeft2': 'Every digit moves 2 places to the left. The dot stays.',
    'shiftRight': 'Every digit moves 1 place to the right. The dot stays.',
    'tenthsTimes': '{b} groups of {a} tenths.',
    'tenthsBack': '{a} tenths.',
    // percent
    'pct10': 'Each bar is 10%.',
    'pct100': 'Percent means out of 100: {a} of the 100 squares.',
    'pctAll': '100% is all of it.',
    'pctFrac': '{a}% is 1 part of {b}.',
    'pctQuarters': '75% is 3 quarters.',
    'pctTens': 'Find 10% first, then take {a} of those.',
    'pctFive': '10% first. 5% is half of that.',
    'pctFifteen': '10% and then 5% more, which is half of 10%.',
    'saleLeft': '{a} comes off the price.',
    // ratio and rate
    'ratioTimes': 'The recipe was made {a} times over.',
    'ratioBoth': 'So both fruits are × {a}.',
    'ratioCheck': 'The same taste means both fruits are multiplied by the same number.',
    'ratioSameTimes': 'Check each mix.',
    'unitRate': 'First find the price of one.',
    'unitTimes': 'Then {a} of them.',
    // puzzles
    'takeKnown': 'Take away the part you know.',
    'sameCutSub': 'Cut both the same, then take away.',
    'sameBottomSub': 'The pieces are already the same size. Take away.',
    'sameCutAll': 'Cut the whole into {a} equal pieces.',
    'fillOne': 'The whole is 1. What is left is the missing part.',
    'eatEach': 'Eat 1 part of {a} from what is left.',
    'shareCakes': 'Cut each cake into {a}. Every child gets 1 piece of each cake: {b} pieces.',
    'shareCakes1': 'Cut the cake into {a}. Every child gets 1 piece.',
    // what went wrong (Candy)
    'oopsTurned': 'A box turned around is the same box. 2 × 6 and 6 × 2 count once.',
    'oopsTimesBoth': 'Whatever happens to the bottom must happen to the top.',
    'oopsWhole1': 'A whole cake is {a} slices, not 1.',
    'oopsMixAdd': 'Each whole cake has {a} slices, not 1.',
    'oopsTops': 'Only same size pieces can be added. Cut them the same first.',
    'oopsTimesAdd': 'Times, not plus: count the small pieces.',
    'oopsScoopAdd': 'Each whole gives {a} scoops: that is times.',
    'oopsSwapDec': 'The tenths and hundredths got swapped. Full rows are tenths.',
    'oopsDecPlace': 'One place off. A tenth is 0.1, a hundredth is 0.01.',
    'oopsLineFrom': 'Count the steps from {a}, the left end.',
    'oopsDecLen': 'More digits does not mean bigger. Compare place by place.',
    'oopsDots': 'The digits were lined up at the end, not at the dot.',
    'oopsShift': 'Count the places the digits move.',
    'oopsAddTen': '× {a} is not + {a}. The digits move, the dot stays.',
    'oopsPctBar': 'Each bar is 10%, not 1%.',
    'oopsSaleOff': 'That is what comes off. The new price is what is left.',
    'oopsRatioAdd': 'Adding the same amount changes the taste. Multiply both.',
    'oopsRateAdd': 'Find the price of one first.',
    'oopsNaive': 'Each time it is a part of what is left, not of the start.',
    ...DESERT_WORDS,
    ...VOLCANO_WORDS,
    ...SPACE_WORDS,
  },
};

let lang = 'en';
export const setLang = l => { if (WORDS[l]) lang = l; };

export function say(key, vars = {}) {
  const t = WORDS[lang][key] ?? WORDS.en[key];
  if (t === undefined) { console.warn('no sentence for', key); return ''; }
  return t.replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ''));
}
